version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    labels:
      - "co.elastic.logs/disable=true"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - esnet
    labels:
      - "co.elastic.logs/disable=true"
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.0
    entrypoint: /usr/local/bin/docker-entrypoint
    command: --strict.perms=false -e
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #ports:
    #  - 5601:5601
    labels:
      - "co.elastic.logs/disable=true"
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - esnet

  nginx:
    image: nginx
    volumes:
      - ./nginx/index.html:/var/www/app/index.html
    ports:
      - 8080:80
    labels:
      - "co.elastic.logs/module=nginx"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
